import Head from 'next/head'
import Image from 'next/image'
import About from '../components/About'
import Main from '../components/Main'
import ProjectsDemo from '../components/ProjectsDemo'
import Skills from '../components/Skills'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Infernal Dimension</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Main />
      <About />
      <Skills />
      <ProjectsDemo />
    </div>
  )
}
